### ISSUE TITLE
疑似和失败的不能写入数据库

### ISSUE THREAD

**Issue by zhychhit** [sy-records/ty-baidu-textcensor#3]
经测试，疑似和审核失败的评论并不能变为待审核状态，而是直接像正常评论一样发出去了

$comment['status'] = 'waiting';

该语句并没有达到预期效果

**Comment by sy-records** [comment]
ty版本以及php版本

**Comment by zhychhit** [comment]
typecho 1.1
PHP 5.6

**Comment by sy-records** [comment]
测试正常。

![image](https://user-images.githubusercontent.com/33931153/90090737-62efd700-dd57-11ea-85dd-403d0ad147e4.png)

**Comment by zhychhit** [comment]
发现是和handsome插件冲突了
